### ISSUE TITLE
Crash before game initialization

### ISSUE THREAD

**Issue by Xanatios** [AetherLegacyPro/AetherLegacyDeparture#4]
Hey, I've just added Aether Legacy Departure to my heavily modded environment. Unfortunately, it crashes before reaching the main menu. It was working just fine when I was using the "original" Aether mod (aether-1.7.10-v1.1.2.3.jar).

I'd really like to change to your fork though, it's looking awesome!
Any help would be much appreciated 😄 

[crash-2024-06-22_12.36.49-client.txt](https://github.com/user-attachments/files/15936227/crash-2024-06-22_12.36.49-client.txt)

**Comment by AetherLegacyPro** [comment]
Issue will be fixed in V1.03
If you want to use the copper and netherite misc items you will need to enable them in the config
