### ISSUE TITLE
Random "Fall Damage" death

### ISSUE THREAD

**Issue by 9182736450typist** [AetherLegacyPro/AetherLegacyDeparture#5]
I was playing survival minecraft with this mod yesterday. I had an aerbunny on, I was on peaceful mode, and suddenly, I got a random fall damage death which insta-killed me.

**Comment by AetherLegacyPro** [comment]
I cannot recreate the issue, need more information on what exactly happened.(Were you fighting something? Was their a major lag spike.) You likely experienced lag when you equipped the aerbunny so while you thought it was on your head it was not -> I would try installing angelica with aether departure as it will help you immensely.

**Comment by 9182736450typist** [comment]
Angelica crashes my game and doesn't work with any shaders.
