### ISSUE TITLE
Crash if attack Valkyrie in this place

### ISSUE THREAD

**Issue by dildobiggens** [AetherLegacyPro/AetherLegacyDeparture#7]
![2024-06-23_14 27 26](https://github.com/AetherLegacyPro/AetherLegacyDeparture/assets/129117917/5812ead3-d41f-42cc-8848-d8fb7674cbfb)

[crash-2024-06-23_14.19.53-client.txt](https://github.com/user-attachments/files/15944322/crash-2024-06-23_14.19.53-client.txt)

**Comment by AetherLegacyPro** [comment]
Alright this issue is fixed in the next patch, V1.04. It only happens when attacking them with an empty hand, I will wait a few days before uploading the patch to see if any other bugs or changes arise.
